/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mariel
 */


public class logIn extends javax.swing.JPanel {

    /**
     * Creates new form logIn
     */
    public logIn() {
        
         
        initComponents();
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsername1 = new javax.swing.JTextField();
        btnlogIn = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to capture it! Desktop App");
        add(jLabel1);
        jLabel1.setBounds(280, 140, 469, 55);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        add(jLabel3);
        jLabel3.setBounds(230, 300, 150, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username:");
        add(jLabel4);
        jLabel4.setBounds(230, 220, 150, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username:");
        add(jLabel5);
        jLabel5.setBounds(230, 220, 150, 30);

        txtUsername1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUsername1.setText("Enter Username");
        txtUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsername1ActionPerformed(evt);
            }
        });
        add(txtUsername1);
        txtUsername1.setBounds(390, 220, 140, 30);

        btnlogIn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnlogIn.setText("Log In");
        btnlogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogInActionPerformed(evt);
            }
        });
        add(btnlogIn);
        btnlogIn.setBounds(370, 420, 140, 30);

        txtPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPassword.setText("Enter Password");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword);
        txtPassword.setBounds(390, 310, 140, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\images\\cameraDesk.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(-30, -10, 1060, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsername1ActionPerformed

    private void btnlogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogInActionPerformed
       
        String username = txtUsername1.getText();
        String password = txtPassword.getText();
        
        if(username == "admin" && password == "hello")
        {
            System.out.println("Welcome");
        }
        
    }//GEN-LAST:event_btnlogInActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername1;
    // End of variables declaration//GEN-END:variables
}
